const materiList = [
  {
    id: "izhar-halqi",
    nama: "Izhar Halqi",
    kategori: "Nun Sukun & Tanwin",
    arab: "إِظْهَارٌ حَلْقِيٌّ",
    singkat: "Dibaca jelas tanpa dengung",
    huruf: ["ء", "ه", "ع", "ح", "غ", "خ"],
    penjelasan:
      "Izhar Halqi terjadi jika nun sukun (نْ) atau tanwin bertemu huruf halqi. Dibaca jelas tanpa dengung.",
    caraBaca:
      "Ucapkan bunyi 'N' dengan tegas tanpa dengung.",
    contohArab: "مِنْ هَادٍ",
    contohLatin: "Min haadin",
    contohArti: "Dari pemberi petunjuk",
    warna: "#E8F4F0",
    warnaAksen: "#2D7A5F",
  },
  {
    id: "idgham-bigunnah",
    nama: "Idgham Bighunnah",
    kategori: "Nun Sukun & Tanwin",
    arab: "إِدْغَامٌ بِغُنَّةٍ",
    singkat: "Dimasukkan dengan dengung",
    huruf: ["ي", "ن", "م", "و"],
    penjelasan:
      "Nun sukun atau tanwin dilebur dengan dengung.",
    caraBaca:
      "Masukkan bunyi nun dan dengungkan 2 harakat.",
    contohArab: "مَنْ يَعْمَلْ",
    contohLatin: "May ya'mal",
    contohArti: "Barangsiapa yang mengerjakan",
    warna: "#EEF0F8",
    warnaAksen: "#3D4D9A",
  },
  {
    id: "idgham-bilagunnah",
    nama: "Idgham Bilaghunnah",
    kategori: "Nun Sukun & Tanwin",
    arab: "إِدْغَامٌ بِلَا غُنَّةٍ",
    singkat: "Tanpa dengung",
    huruf: ["ل", "ر"],
    penjelasan:
      "Nun sukun dilebur tanpa dengung.",
    caraBaca:
      "Langsung gabungkan tanpa ditahan.",
    contohArab: "مِنْ رَبِّكَ",
    contohLatin: "Mir robbika",
    contohArti: "Dari Tuhanmu",
    warna: "#F5EEF8",
    warnaAksen: "#7D3C98",
  },
  {
    id: "iqlab",
    nama: "Iqlab",
    kategori: "Nun Sukun & Tanwin",
    arab: "إِقْلَابٌ",
    singkat: "Nun jadi Mim",
    huruf: ["ب"],
    penjelasan:
      "Nun berubah menjadi Mim dengan dengung.",
    caraBaca:
      "Ganti N jadi M dan dengungkan.",
    contohArab: "أَنْبِئْهُمْ",
    contohLatin: "Ambi'hum",
    contohArti: "Beritahukanlah kepada mereka",
    warna: "#FEF5E7",
    warnaAksen: "#C0872F",
  },
  {
    id: "ikhfa-haqiqi",
    nama: "Ikhfa Haqiqi",
    kategori: "Nun Sukun & Tanwin",
    arab: "إِخْفَاءٌ حَقِيقِيٌّ",
    singkat: "Samar dengan dengung",
    huruf: ["ت","ث","ج","د","ذ","ز","س","ش","ص","ض","ط","ظ","ف","ق","ك"],
    penjelasan:
      "Nun disamarkan dengan dengung.",
    caraBaca:
      "Samarkan bunyi N dan tahan 2-3 harakat.",
    contohArab: "مَنْ كَانَ",
    contohLatin: "Mang kaana",
    contohArti: "Barangsiapa yang ada",
    warna: "#FDEBD0",
    warnaAksen: "#A04000",
  },
  {
    id: "mad-thobii",
    nama: "Mad Thabi'i",
    kategori: "Mad",
    arab: "مَدٌّ طَبِيعِيٌّ",
    singkat: "Panjang 2 harakat",
    huruf: ["ا", "و", "ي"],
    penjelasan:
      "Mad dasar 2 harakat.",
    caraBaca:
      "Panjangkan 2 ketukan.",
    contohArab: "قَالَ",
    contohLatin: "Qaala",
    contohArti: "Dia berkata",
    warna: "#E8F8F5",
    warnaAksen: "#1A7A6A",
  },
  {
    id: "mad-wajib-muttasil",
    nama: "Mad Wajib Muttasil",
    kategori: "Mad",
    arab: "مَدٌّ وَاجِبٌ مُتَّصِلٌ",
    singkat: "4-5 harakat",
    huruf: ["Mad", "+", "ء"],
    penjelasan:
      "Mad bertemu hamzah satu kata.",
    caraBaca:
      "Panjangkan 4-5 harakat.",
    contohArab: "جَاءَ",
    contohLatin: "Jaa-a",
    contohArti: "Telah datang",
    warna: "#EAF2FB",
    warnaAksen: "#1A5276",
  },
  {
    id: "ghunnah",
    nama: "Ghunnah",
    kategori: "Tasydid",
    arab: "غُنَّةٌ",
    singkat: "Dengung",
    huruf: ["نّ", "مّ"],
    penjelasan:
      "Nun/Mim tasydid dibaca dengung.",
    caraBaca:
      "Tahan 2 harakat.",
    contohArab: "إِنَّ",
    contohLatin: "Inna",
    contohArti: "Sesungguhnya",
    warna: "#F9EBEA",
    warnaAksen: "#922B21",
  },

  {
    id: "ikhfa-syafawi",
    nama: "Ikhfa Syafawi",
    kategori: "Mim Sukun",
    arab: "إِخْفَاءٌ شَفَوِيٌّ",
    singkat: "Mim samar",
    huruf: ["ب"],
    penjelasan:
      "Mim sukun bertemu Ba dibaca samar.",
    caraBaca:
      "Dengungkan 2 harakat.",
    contohArab: "تَرْمِيهِمْ بِحِجَارَةٍ",
    contohLatin: "Tarmihim",
    contohArti: "Melempari mereka",
    warna: "#E8F6F3",
    warnaAksen: "#117864",
  },
  {
    id: "idgham-mimi",
    nama: "Idgham Mimi",
    kategori: "Mim Sukun",
    arab: "إِدْغَامٌ",
    singkat: "Mim bertemu Mim",
    huruf: ["م"],
    penjelasan:
      "Mim sukun bertemu Mim dilebur.",
    caraBaca:
      "Dengungkan 2 harakat.",
    contohArab: "لَهُمْ مَا",
    contohLatin: "Lahumma",
    contohArti: "Bagi mereka",
    warna: "#F4ECF7",
    warnaAksen: "#6C3483",
  },
  {
    id: "izhar-syafawi",
    nama: "Izhar Syafawi",
    kategori: "Mim Sukun",
    arab: "إِظْهَارٌ",
    singkat: "Mim jelas",
    huruf: ["selain م dan ب"],
    penjelasan:
      "Mim dibaca jelas.",
    caraBaca:
      "Tanpa dengung.",
    contohArab: "لَكُمْ دِينُكُمْ",
    contohLatin: "Lakum diinukum",
    contohArti: "Untukmu agamamu",
    warna: "#FEF9E7",
    warnaAksen: "#B7950B",
  },
  {
    id: "qalqalah",
    nama: "Qalqalah",
    kategori: "Hukum Bacaan",
    arab: "قَلْقَلَةٌ",
    singkat: "Pantulan huruf",
    huruf: ["ق","ط","ب","ج","د"],
    penjelasan:
      "Huruf dipantulkan saat sukun.",
    caraBaca:
      "Pantulkan ringan.",
    contohArab: "أَحَدْ",
    contohLatin: "Ahad",
    contohArti: "Yang Maha Esa",
    warna: "#EBF5FB",
    warnaAksen: "#1F618D",
  },
  {
    id: "mad-jaiz-munfasil",
    nama: "Mad Jaiz Munfasil",
    kategori: "Mad",
    arab: "مَدٌّ جَائِزٌ",
    singkat: "4-5 harakat beda kata",
    huruf: ["Mad", "+", "ء"],
    penjelasan:
      "Mad bertemu hamzah beda kata.",
    caraBaca:
      "Panjangkan 4-5 harakat.",
    contohArab: "فِي أَنْفُسِكُمْ",
    contohLatin: "Fii anfusikum",
    contohArti: "Dalam dirimu",
    warna: "#EAF2F8",
    warnaAksen: "#2E86C1",
  },
  {
  id: "idgham-mitslain",
  nama: "Idgham Mitslain",
  kategori: "Huruf Sama",
  arab: "إِدْغَامُ مِثْلَيْنِ",
  singkat: "Huruf sama dilebur",
  huruf: ["contoh: ب + ب"],
  penjelasan:
    "Terjadi jika dua huruf yang sama bertemu, maka dibaca lebur seperti tasydid.",
  caraBaca:
    "Gabungkan kedua huruf dan tekan seperti huruf bertasydid.",
  contohArab: "اِضْرِبْ بِعَصَاكَ",
  contohLatin: "Idrib bi'asaaka",
  contohArti: "Pukullah dengan tongkatmu",
  warna: "#F4ECF7",
  warnaAksen: "#6C3483",
},
{
  id: "idgham-mutaqaribain",
  nama: "Idgham Mutaqaribain",
  kategori: "Huruf Dekat",
  arab: "إِدْغَامُ مُتَقَارِبَيْنِ",
  singkat: "Huruf hampir sama dilebur",
  huruf: ["ق + ك"],
  penjelasan:
    "Terjadi ketika dua huruf makhrajnya berdekatan.",
  caraBaca:
    "Dibaca lebur dengan tekanan ringan.",
  contohArab: "نَخْلُقْكُمْ",
  contohLatin: "Nakhlukkum",
  contohArti: "Kami menciptakan kalian",
  warna: "#EBF5FB",
  warnaAksen: "#1F618D",
},
{
  id: "mad-lin",
  nama: "Mad Lin",
  kategori: "Mad",
  arab: "مَدُّ اللِّينِ",
  singkat: "Mad lembut",
  huruf: ["و", "ي"],
  penjelasan:
    "Mad yang terjadi ketika huruf lin diwaqafkan.",
  caraBaca:
    "Dibaca lembut dan dipanjangkan 2–4 harakat.",
  contohArab: "خَوْفٍ",
  contohLatin: "Khauf",
  contohArti: "Rasa takut",
  warna: "#E8F8F5",
  warnaAksen: "#1A7A6A",
},
{
  id: "mad-arid-lissukun",
  nama: "Mad Arid Lissukun",
  kategori: "Mad",
  arab: "مَدٌّ عَارِضٌ لِلسُّكُونِ",
  singkat: "Mad karena waqaf",
  huruf: ["Mad + sukun"],
  penjelasan:
    "Terjadi saat berhenti (waqaf) pada akhir kata.",
  caraBaca:
    "Boleh dibaca 2, 4, atau 6 harakat.",
  contohArab: "الْعَالَمِينَ",
  contohLatin: "Al-'aalamiin",
  contohArti: "Seluruh alam",
  warna: "#EAF2F8",
  warnaAksen: "#2E86C1",
},
{
  id: "waqaf-la",
  nama: "Waqaf La",
  kategori: "Tanda Waqaf",
  arab: "لَا",
  singkat: "Tidak boleh berhenti",
  huruf: ["لا"],
  penjelasan:
    "Menandakan tidak boleh berhenti pada tempat tersebut.",
  caraBaca:
    "Harus dilanjutkan ke kata berikutnya.",
  contohArab: "لَا تَقْرَبُوا",
  contohLatin: "La taqrabu",
  contohArti: "Janganlah kalian mendekati",
  warna: "#FDEDEC",
  warnaAksen: "#C0392B",
},
{
  id: "waqaf-mim",
  nama: "Waqaf Mim",
  kategori: "Tanda Waqaf",
  arab: "م",
  singkat: "Harus berhenti",
  huruf: ["م"],
  penjelasan:
    "Menandakan wajib berhenti.",
  caraBaca:
    "Harus berhenti sejenak.",
  contohArab: "وَاللَّهُ أَعْلَمُ",
  contohLatin: "Wallahu a'lam",
  contohArti: "Allah Maha Mengetahui",
  warna: "#FADBD8",
  warnaAksen: "#922B21",
},
{
  id: "tafkhim-tarqiq",
  nama: "Tafkhim & Tarqiq",
  kategori: "Pelafalan",
  arab: "تَفْخِيمٌ وَتَرْقِيقٌ",
  singkat: "Tebal dan tipis",
  huruf: ["ر", "ل"],
  penjelasan:
    "Cara membaca huruf dengan tebal (tafkhim) atau tipis (tarqiq).",
  caraBaca:
    "Sesuaikan dengan harakat dan posisi huruf.",
  contohArab: "رَبِّ",
  contohLatin: "Rabbi",
  contohArti: "Tuhanku",
  warna: "#FEF9E7",
  warnaAksen: "#B7950B",
},
{
  id: "lam-jalalah",
  nama: "Lam Jalalah",
  kategori: "Pelafalan",
  arab: "اللَّهُ",
  singkat: "Lam pada lafadz Allah",
  huruf: ["ل"],
  penjelasan:
    "Cara membaca lam pada lafadz Allah bisa tebal atau tipis.",
  caraBaca:
    "Tebal jika sebelumnya fathah/dhommah, tipis jika kasrah.",
  contohArab: "اللَّهُ أَكْبَرُ",
  contohLatin: "Allahu akbar",
  contohArti: "Allah Maha Besar",
  warna: "#F5EEF8",
  warnaAksen: "#7D3C98",
}
];

export default materiList;